<Project>
  <PropertyGroup>
    <Version>3.0.0</Version>
    <FileVersion>3.0.0.0</FileVersion>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <Company>UGSo</Company>
    <Authors>UGSo</Authors>
    <Copyright>© 2026 UGSo</Copyright>
    <RepositoryUrl>https://github.com/rockbaer2007/HADash</RepositoryUrl>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
