<Project>
  <PropertyGroup>
    <Version>0.9.4-preview</Version>
    <FileVersion>0.9.4.0</FileVersion>
    <AssemblyVersion>0.9.4.0</AssemblyVersion>
    <Company>UGSo</Company>
    <Authors>UGSo</Authors>
    <Copyright>© 2026 UGSo</Copyright>
    <RepositoryUrl>https://github.com/rockbaer2007/HADash</RepositoryUrl>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
